version: '3.8'

networks:
  net:
    driver: bridge

services:
  redis:
    container_name: redis
    image: redis:latest
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 2s
      retries: 3
    networks:
      - net
    restart: always

  # golang-app:
  #   container_name: golang-app
  #   build:
  #     dockerfile: Dockerfile
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   networks:
  #     - net